Copy RGL library to ouput directory
RobotecAI/o3de-rgl-gem pull request #19
Opened 2023-12-21 17:15 UTC by michalpelka

Used `ly_add_target_files` macro to copy RGL shared library.

According to documentation `ly_add_target_files` should copy given file next to target. On 2301.1 it resolves #18 .

2024-01-02 09:09 UTC, PiotrMrozik requested changes

2024-01-02 09:09 UTC, PiotrMrozik commented on Code/CMakeLists.txt
> +link_directories(/home/michalpelka/github/o3de-rgl-gem/Code/3rdParty/RobotecGPULidar/)
I know this is a temporary solution, but I cannot accept that.

2024-01-02 21:37 UTC, michalpelka commented on Code/CMakeLists.txt
> +link_directories(/home/michalpelka/github/o3de-rgl-gem/Code/3rdParty/RobotecGPULidar/)
```suggestion

```

2024-01-09 11:54 UTC, PiotrMrozik approved these changes

2024-01-09 11:58 UTC, adamdbrw approved these changes

2024-01-09 11:58 UTC, merged